#!/bin/bash

# Kill any existing instances to avoid "ghost" loops
pkill -f "pomo_timer_loop"

# Run the loop in the background
(
    exec -a pomo_timer_loop bash -c '
    # Regex pattern for "number:number"
    RE="^[0-9]+:[0-9]+$"
    STOP_HOOK="$HOME/.pomodoro/hooks/stop"

    while true; do
        STATUS=$(pomo status -f "%r")

    	if [[ "$STATUS" == "0:00" ]]; then
	    bash "$STOP_HOOK"
            break
        elif [[ "$STATUS" =~ $RE ]]; then
            echo "$STATUS" > /tmp/pomo_status
    	else
	    break
	fi

        sleep 5
    done
    '
) > /dev/null 2>&1 &

exit 0
